groups:
  - name: test-alert
    rules:
      - alert: TestMailAlert
        expr: vector(1)
        for: 10s
        labels:
          severity: test
        annotations:
          summary: "This is a test alert"
