global:
  scrape_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'azure-api'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets:
          - api-customer-zaroor-d9hagpfvdqghd3dg.centralindia-01.azurewebsites.net
        labels:
          group: 'demo'

rule_files:
  - alerts.yml
